# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-nvm-{{ checksum ".nvmrc" }}
          # fallback to using the latest cache if no exact match is found
          - v1-nvm-

      - run:
          name: Install node via .nvmrc
          command: |
            set +e
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install
            nvm use
            nvm alias default $(cat .nvmrc)

            # Each step uses the same `$BASH_ENV`, so need to modify it
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV

      - run:
          name: Install yarn
          command: npm install -g yarn

      - save_cache:
          paths:
            - /opt/circleci/.nvm
          key: v1-nvm-{{ checksum ".nvmrc" }}

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # clean
      - run: docker network prune --force

      # lint
      - run: yarn lint

      # build
      - run: yarn styleguide:build # prestyleguide:build runs a pkg build

      # test
      - run: DEBUG=webjerk* npm test -- --verbose

      # report
      - run:
          name: send report to github
          command: |
            echo "machine surge.surge.sh" >> ~/.netrc
            echo "    login $SURGE_LOGIN" >> ~/.netrc
            echo "    password $SURGE_TOKEN" >> ~/.netrc
            git config --global user.email "gh-pages@localhost" && git config --global user.name "npm gh-pages"
            if [ "$CIRCLE_BRANCH" != "master" ]; then yarn ci:update-pull-request-with-styleguide || true; fi

      # cut a release
      - run:
          name: release
          command: |
            node scripts/ci-post-test.js

      # https://circleci.com/docs/2.0/artifacts/
      - store_artifacts:
          path: snaps/run
